### ISSUE TITLE
Questions about the "train.json" file

### ISSUE THREAD

**Issue by LHS23** [premsrit/SPARTUNQChain#1]
Hello, I would like to ask a question. When I run the command "python main.py --epoch 8 --train_file ORIGIN --test_file ORIGIN --train_size 1000000 --test_size 1000000 --cuda 0 --lr 8e-6 --batch_size 8", I get a message saying "FileNotFoundError: [Errno 2] No such file or directory: 'DataSet/train.json'". Meanwhile, there is no "train.json" file in the root directory of the Google Drive folder you provided. I don't know if it's because you haven't uploaded the file or if I'm running the command incorrectly. Similarly, the command "python main_rel.py --epoch 8 --train_file ORIGIN --test_file ORIGIN --train_size 1000000 --test_size 1000000 --cuda 0 --lr 8e-6 --batch_size 8" also has the same issue.
Looking forward to your reply, thank you!
![屏幕截图 2024-09-27 162914](https://github.com/user-attachments/assets/2f3e99a4-efc3-4b3a-8f09-08ceae42bc64)
![屏幕截图 2024-09-27 161555](https://github.com/user-attachments/assets/a7710930-b956-4d21-9d76-181a062ba64b)

**Comment by premsrit** [comment]
I'm sorry for the inconvenience. Let me update the dataset folder; it seems to be missing some new files. This should be resolved by now.
If you have a problem running experiments regarding STEPGAME, please download it separately and include it in the same dataset folder. 
Thank you for contacting me.

**Comment by LHS23** [comment]
Thanks for your reply, the command has been executed successfully now.
